name: client-tests-workflow

on: pull_request

jobs:
  test-client:
    runs-on: macos-13
    steps:
      - name: Check out your code 
        uses: actions/checkout@v2
      - name: Goto client and run tests
        run: cd client && npm i && npm test
